# Generated by Django 3.2.15 on 2022-10-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juniors', '0007_auto_20221020_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junior',
            name='password',
        ),
        migrations.AlterField(
            model_name='junior',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.country'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Linkedin'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.position'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='junior',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Telegram'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='url_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
