# Generated by Django 3.2.15 on 2022-10-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juniors', '0008_auto_20221024_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(default='client', max_length=100, verbose_name='URL'),
        ),
    ]
