# Generated by Django 3.2.15 on 2022-12-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juniors', '0009_alter_position_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junior',
            name='position',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(default='backend', max_length=100, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Messengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эл. почта для связи')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вебсайт')),
                ('whatsup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Whatsapp')),
                ('viber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Viber')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Facebook')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Вконтакте')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Instagram')),
                ('behance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Behance')),
                ('pinterest', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль Piterest')),
                ('junior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='juniors.junior')),
            ],
            options={
                'verbose_name': 'Мессенджер',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
        migrations.CreateModel(
            name='JunSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='juniors.junior')),
                ('junior_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior', to='juniors.junior')),
            ],
        ),
        migrations.AddConstraint(
            model_name='junschedule',
            constraint=models.CheckConstraint(check=models.Q(('time__in', ('13:00', '14:00', '15:00'))), name='valid_hours_constraint'),
        ),
        migrations.AddConstraint(
            model_name='junschedule',
            constraint=models.UniqueConstraint(fields=('junior_id', 'client_id', 'date', 'time'), name='single_appointment_constraint'),
        ),
    ]
