# Generated by Django 3.2.15 on 2022-09-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hardskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Хард-скилл',
                'verbose_name_plural': 'Хард-скиллы',
            },
        ),
        migrations.CreateModel(
            name='Junior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('linkedin', models.CharField(max_length=100, null=True, verbose_name='Профиль Linkedin')),
                ('telegram', models.CharField(max_length=100, null=True, verbose_name='Профиль Telegram')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('url_img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('descr', models.TextField(null=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('exp', models.CharField(max_length=20, null=True)),
                ('language', models.CharField(max_length=100, null=True, verbose_name='Языки')),
                ('salary', models.IntegerField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.country')),
                ('hdskills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.hardskills', verbose_name='Хард-скиллы')),
            ],
            options={
                'verbose_name': 'Джуны',
                'verbose_name_plural': 'Джуны',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JuniorSoftskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juniors.junior')),
            ],
            options={
                'verbose_name': 'Связь Джун - Софт-скилл',
                'verbose_name_plural': 'Связи Джун - Софт-скилл',
            },
        ),
        migrations.CreateModel(
            name='JuniorTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juniors.junior')),
            ],
            options={
                'verbose_name': 'Связь Джун - Технология',
                'verbose_name_plural': 'Связи Джун - Технология',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Специальности',
                'verbose_name_plural': 'Специальности',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100)),
                ('jun', models.ManyToManyField(through='juniors.JuniorTools', to='juniors.Junior')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Стек технологий',
            },
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('jun', models.ManyToManyField(through='juniors.JuniorSoftskills', to='juniors.Junior')),
            ],
            options={
                'verbose_name': 'Софт-скилл',
                'verbose_name_plural': 'Софт-скиллы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='juniortools',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juniors.tools'),
        ),
        migrations.AddField(
            model_name='juniorsoftskills',
            name='softskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juniors.softskills'),
        ),
        migrations.CreateModel(
            name='JuniorHardskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardskill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juniors.hardskills')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juniors.junior')),
            ],
            options={
                'verbose_name': 'Связь Джун - Хард-скилл',
                'verbose_name_plural': 'Связи Джун - Хард-скилл',
                'unique_together': {('junior', 'hardskill')},
            },
        ),
        migrations.AddField(
            model_name='junior',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.position'),
        ),
        migrations.AddField(
            model_name='junior',
            name='sfskills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.softskills', verbose_name='Софт-скиллы'),
        ),
        migrations.AddField(
            model_name='junior',
            name='tlls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='juniors.tools', verbose_name='Стек технологий'),
        ),
        migrations.AddField(
            model_name='hardskills',
            name='jun',
            field=models.ManyToManyField(through='juniors.JuniorHardskills', to='juniors.Junior'),
        ),
        migrations.AlterUniqueTogether(
            name='juniortools',
            unique_together={('junior', 'tool')},
        ),
        migrations.AlterUniqueTogether(
            name='juniorsoftskills',
            unique_together={('junior', 'softskill')},
        ),
    ]
