# Generated by Django 3.2.15 on 2022-09-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juniors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junior',
            name='hdskills',
        ),
        migrations.RemoveField(
            model_name='junior',
            name='sfskills',
        ),
        migrations.RemoveField(
            model_name='junior',
            name='tlls',
        ),
    ]
