# Generated by Django 3.2.15 on 2022-10-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juniors', '0002_auto_20220929_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.FileField(blank=True, upload_to='country', verbose_name='Иконка-флаг'),
        ),
        migrations.AddField(
            model_name='junior',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Пароль'),
        ),
    ]
